//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_reservation
    {
        public int id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual t_book t_book { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
